// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import SortingController from "./sorting_controller"
import KeywordsSortingController from "./keywords_sorting_controller"
import SubmitOnChangeController from "./submit_on_change_controller"
import KeywordsChartModalController from "./keywords_chart_modal_controller"
import TechnicalSeoModalController from "./technical_seo_modal_controller"

application.register("hello", HelloController)
application.register("sorting", SortingController)
application.register("keywords-sorting", KeywordsSortingController)
application.register("submit-on-change", SubmitOnChangeController)
application.register("keywords-chart-modal", KeywordsChartModalController)
application.register("technical-seo-modal", TechnicalSeoModalController)