require 'google/ads/google_ads'

class GoogleAds::KeywordsService < BaseService
  def initialize(url: nil, keywords: nil, country: nil)
    @url = url
    @keywords = keywords
    @country_code = country
    # ENV['HOME']/google_ads_config.rb when called without parameters
    @client = Google::Ads::GoogleAds::GoogleAdsClient.new('./config/google_ads_config.rb')
  end

  def call(action: :get_keyword_ideas)
    send(action)
  end

  def get_keyword_ideas
    seed = build_seed
    geo_target_constant = @country_code ? [geo_target_constants.find { |geo| geo[:country_code].downcase == @country_code.downcase }&.dig(:resource_name)] : []

    response = @client.service.keyword_plan_idea.generate_keyword_ideas(
      customer_id: "#{Rails.application.credentials.google_ads_api_customer_id}",
      # language: "#{language_constants.find { |lang| lang[:code].downcase == @country_code.downcase }&.dig(:resource_name)}",
      geo_target_constants: geo_target_constant,
      keyword_plan_network: :GOOGLE_SEARCH,
      **seed
    )

    response.map do |result|
      keyword = result.text
      metrics = result.keyword_idea_metrics
    
      avg_monthly_searches = metrics&.avg_monthly_searches
      competition = metrics&.competition
      competition_index = metrics&.competition_index
      low_top_of_page_bid_micros = metrics&.low_top_of_page_bid_micros
      high_top_of_page_bid_micros = metrics&.high_top_of_page_bid_micros
    
      {
        keyword: keyword,
        avg_monthly_searches: avg_monthly_searches,
        competition: competition,
        competition_index: competition_index,
        low_top_of_page_bid_micros: low_top_of_page_bid_micros,
        high_top_of_page_bid_micros: high_top_of_page_bid_micros
      }
    end
  end

  def get_keyword_historical_metrics
    geo_target_constant = @country_code ? [geo_target_constants.find { |geo| geo[:country_code].downcase == @country_code.downcase }&.dig(:resource_name)] : []
    response = @client.service.keyword_plan_idea.generate_keyword_historical_metrics(
      customer_id: "#{Rails.application.credentials.google_ads_api_customer_id}",
      keywords: @keywords,
      geo_target_constants: geo_target_constant
    )
    response.results.map do |result|
      {
        keyword: result.text,
        avg_monthly_searches: result.keyword_metrics.avg_monthly_searches,
        competition: result.keyword_metrics.competition,
        competition_index: result.keyword_metrics.competition_index,
        low_top_of_page_bid_micros: result.keyword_metrics.low_top_of_page_bid_micros,
        high_top_of_page_bid_micros: result.keyword_metrics.high_top_of_page_bid_micros,
        monthly_search_volumes: result.keyword_metrics.monthly_search_volumes.map do |monthly_search_volume|
          {
            year: monthly_search_volume.year,
            month: monthly_search_volume.month,
            monthly_searches: monthly_search_volume.monthly_searches
          }
        end
      }
    end
  end

  def build_seed
    result = {}
    if @keywords.present?
      result[:keyword_seed] = @client.resource.keyword_seed do |s|
        @keywords.each do |kw|
          s.keywords << kw.strip.encode('UTF-8')
        end
      end
    end
    if @url.present?
      result[:url_seed] = @client.resource.url_seed do |s|
        s.url = @url
      end
    end
    raise "No seeds provided" if result.empty?
    result
  end

  def geo_target_constants
    [
      {name: "Afghanistan", country_code: "AF", resource_name: "geoTargetConstants/2004"},
      {name: "Albania", country_code: "AL", resource_name: "geoTargetConstants/2008"},
      {name: "Antarctica", country_code: "AQ", resource_name: "geoTargetConstants/2010"},
      {name: "Algeria", country_code: "DZ", resource_name: "geoTargetConstants/2012"},
      {name: "American Samoa", country_code: "AS", resource_name: "geoTargetConstants/2016"},
      {name: "Andorra", country_code: "AD", resource_name: "geoTargetConstants/2020"},
      {name: "Angola", country_code: "AO", resource_name: "geoTargetConstants/2024"},
      {name: "Antigua and Barbuda", country_code: "AG", resource_name: "geoTargetConstants/2028"},
      {name: "Azerbaijan", country_code: "AZ", resource_name: "geoTargetConstants/2031"},
      {name: "Argentina", country_code: "AR", resource_name: "geoTargetConstants/2032"},
      {name: "Australia", country_code: "AU", resource_name: "geoTargetConstants/2036"},
      {name: "Austria", country_code: "AT", resource_name: "geoTargetConstants/2040"},
      {name: "The Bahamas", country_code: "BS", resource_name: "geoTargetConstants/2044"},
      {name: "Bahrain", country_code: "BH", resource_name: "geoTargetConstants/2048"},
      {name: "Bangladesh", country_code: "BD", resource_name: "geoTargetConstants/2050"},
      {name: "Armenia", country_code: "AM", resource_name: "geoTargetConstants/2051"},
      {name: "Barbados", country_code: "BB", resource_name: "geoTargetConstants/2052"},
      {name: "Belgium", country_code: "BE", resource_name: "geoTargetConstants/2056"},
      {name: "Bhutan", country_code: "BT", resource_name: "geoTargetConstants/2064"},
      {name: "Bolivia", country_code: "BO", resource_name: "geoTargetConstants/2068"},
      {name: "Bosnia and Herzegovina", country_code: "BA", resource_name: "geoTargetConstants/2070"},
      {name: "Botswana", country_code: "BW", resource_name: "geoTargetConstants/2072"},
      {name: "Brazil", country_code: "BR", resource_name: "geoTargetConstants/2076"},
      {name: "Belize", country_code: "BZ", resource_name: "geoTargetConstants/2084"},
      {name: "Solomon Islands", country_code: "SB", resource_name: "geoTargetConstants/2090"},
      {name: "Brunei", country_code: "BN", resource_name: "geoTargetConstants/2096"},
      {name: "Bulgaria", country_code: "BG", resource_name: "geoTargetConstants/2100"},
      {name: "Myanmar (Burma)", country_code: "MM", resource_name: "geoTargetConstants/2104"},
      {name: "Burundi", country_code: "BI", resource_name: "geoTargetConstants/2108"},
      {name: "Belarus", country_code: "BY", resource_name: "geoTargetConstants/2112"},
      {name: "Cambodia", country_code: "KH", resource_name: "geoTargetConstants/2116"},
      {name: "Cameroon", country_code: "CM", resource_name: "geoTargetConstants/2120"},
      {name: "Canada", country_code: "CA", resource_name: "geoTargetConstants/2124"},
      {name: "Cabo Verde", country_code: "CV", resource_name: "geoTargetConstants/2132"},
      {name: "Central African Republic", country_code: "CF", resource_name: "geoTargetConstants/2140"},
      {name: "Sri Lanka", country_code: "LK", resource_name: "geoTargetConstants/2144"},
      {name: "Chad", country_code: "TD", resource_name: "geoTargetConstants/2148"},
      {name: "Chile", country_code: "CL", resource_name: "geoTargetConstants/2152"},
      {name: "China", country_code: "CN", resource_name: "geoTargetConstants/2156"},
      {name: "Christmas Island", country_code: "CX", resource_name: "geoTargetConstants/2162"},
      {name: "Cocos (Keeling) Islands", country_code: "CC", resource_name: "geoTargetConstants/2166"},
      {name: "Colombia", country_code: "CO", resource_name: "geoTargetConstants/2170"},
      {name: "Comoros", country_code: "KM", resource_name: "geoTargetConstants/2174"},
      {name: "Republic of the Congo", country_code: "CG", resource_name: "geoTargetConstants/2178"},
      {name: "Democratic Republic of the Congo", country_code: "CD", resource_name: "geoTargetConstants/2180"},
      {name: "Cook Islands", country_code: "CK", resource_name: "geoTargetConstants/2184"},
      {name: "Costa Rica", country_code: "CR", resource_name: "geoTargetConstants/2188"},
      {name: "Croatia", country_code: "HR", resource_name: "geoTargetConstants/2191"},
      {name: "Cyprus", country_code: "CY", resource_name: "geoTargetConstants/2196"},
      {name: "Czechia", country_code: "CZ", resource_name: "geoTargetConstants/2203"},
      {name: "Benin", country_code: "BJ", resource_name: "geoTargetConstants/2204"},
      {name: "Denmark", country_code: "DK", resource_name: "geoTargetConstants/2208"},
      {name: "Dominica", country_code: "DM", resource_name: "geoTargetConstants/2212"},
      {name: "Dominican Republic", country_code: "DO", resource_name: "geoTargetConstants/2214"},
      {name: "Ecuador", country_code: "EC", resource_name: "geoTargetConstants/2218"},
      {name: "El Salvador", country_code: "SV", resource_name: "geoTargetConstants/2222"},
      {name: "Equatorial Guinea", country_code: "GQ", resource_name: "geoTargetConstants/2226"},
      {name: "Ethiopia", country_code: "ET", resource_name: "geoTargetConstants/2231"},
      {name: "Eritrea", country_code: "ER", resource_name: "geoTargetConstants/2232"},
      {name: "Estonia", country_code: "EE", resource_name: "geoTargetConstants/2233"},
      {name: "South Georgia and the South Sandwich Islands", country_code: "GS", resource_name: "geoTargetConstants/2239"},
      {name: "Fiji", country_code: "FJ", resource_name: "geoTargetConstants/2242"},
      {name: "Finland", country_code: "FI", resource_name: "geoTargetConstants/2246"},
      {name: "France", country_code: "FR", resource_name: "geoTargetConstants/2250"},
      {name: "French Polynesia", country_code: "PF", resource_name: "geoTargetConstants/2258"},
      {name: "French Southern and Antarctic Lands", country_code: "TF", resource_name: "geoTargetConstants/2260"},
      {name: "Djibouti", country_code: "DJ", resource_name: "geoTargetConstants/2262"},
      {name: "Gabon", country_code: "GA", resource_name: "geoTargetConstants/2266"},
      {name: "Georgia", country_code: "GE", resource_name: "geoTargetConstants/2268"},
      {name: "The Gambia", country_code: "GM", resource_name: "geoTargetConstants/2270"},
      {name: "Germany", country_code: "DE", resource_name: "geoTargetConstants/2276"},
      {name: "Ghana", country_code: "GH", resource_name: "geoTargetConstants/2288"},
      {name: "Kiribati", country_code: "KI", resource_name: "geoTargetConstants/2296"},
      {name: "Greece", country_code: "GR", resource_name: "geoTargetConstants/2300"},
      {name: "Grenada", country_code: "GD", resource_name: "geoTargetConstants/2308"},
      {name: "Guam", country_code: "GU", resource_name: "geoTargetConstants/2316"},
      {name: "Guatemala", country_code: "GT", resource_name: "geoTargetConstants/2320"},
      {name: "Guinea", country_code: "GN", resource_name: "geoTargetConstants/2324"},
      {name: "Guyana", country_code: "GY", resource_name: "geoTargetConstants/2328"},
      {name: "Haiti", country_code: "HT", resource_name: "geoTargetConstants/2332"},
      {name: "Heard Island and McDonald Islands", country_code: "HM", resource_name: "geoTargetConstants/2334"},
      {name: "Vatican City", country_code: "VA", resource_name: "geoTargetConstants/2336"},
      {name: "Honduras", country_code: "HN", resource_name: "geoTargetConstants/2340"},
      {name: "Hungary", country_code: "HU", resource_name: "geoTargetConstants/2348"},
      {name: "Iceland", country_code: "IS", resource_name: "geoTargetConstants/2352"},
      {name: "India", country_code: "IN", resource_name: "geoTargetConstants/2356"},
      {name: "Indonesia", country_code: "ID", resource_name: "geoTargetConstants/2360"},
      {name: "Iraq", country_code: "IQ", resource_name: "geoTargetConstants/2368"},
      {name: "Ireland", country_code: "IE", resource_name: "geoTargetConstants/2372"},
      {name: "Israel", country_code: "IL", resource_name: "geoTargetConstants/2376"},
      {name: "Italy", country_code: "IT", resource_name: "geoTargetConstants/2380"},
      {name: "Cote d'Ivoire", country_code: "CI", resource_name: "geoTargetConstants/2384"},
      {name: "Jamaica", country_code: "JM", resource_name: "geoTargetConstants/2388"},
      {name: "Japan", country_code: "JP", resource_name: "geoTargetConstants/2392"},
      {name: "Kazakhstan", country_code: "KZ", resource_name: "geoTargetConstants/2398"},
      {name: "Jordan", country_code: "JO", resource_name: "geoTargetConstants/2400"},
      {name: "Kenya", country_code: "KE", resource_name: "geoTargetConstants/2404"},
      {name: "South Korea", country_code: "KR", resource_name: "geoTargetConstants/2410"},
      {name: "Kuwait", country_code: "KW", resource_name: "geoTargetConstants/2414"},
      {name: "Kyrgyzstan", country_code: "KG", resource_name: "geoTargetConstants/2417"},
      {name: "Laos", country_code: "LA", resource_name: "geoTargetConstants/2418"},
      {name: "Lebanon", country_code: "LB", resource_name: "geoTargetConstants/2422"},
      {name: "Lesotho", country_code: "LS", resource_name: "geoTargetConstants/2426"},
      {name: "Latvia", country_code: "LV", resource_name: "geoTargetConstants/2428"},
      {name: "Liberia", country_code: "LR", resource_name: "geoTargetConstants/2430"},
      {name: "Libya", country_code: "LY", resource_name: "geoTargetConstants/2434"},
      {name: "Liechtenstein", country_code: "LI", resource_name: "geoTargetConstants/2438"},
      {name: "Lithuania", country_code: "LT", resource_name: "geoTargetConstants/2440"},
      {name: "Luxembourg", country_code: "LU", resource_name: "geoTargetConstants/2442"},
      {name: "Madagascar", country_code: "MG", resource_name: "geoTargetConstants/2450"},
      {name: "Malawi", country_code: "MW", resource_name: "geoTargetConstants/2454"},
      {name: "Malaysia", country_code: "MY", resource_name: "geoTargetConstants/2458"},
      {name: "Maldives", country_code: "MV", resource_name: "geoTargetConstants/2462"},
      {name: "Mali", country_code: "ML", resource_name: "geoTargetConstants/2466"},
      {name: "Malta", country_code: "MT", resource_name: "geoTargetConstants/2470"},
      {name: "Mauritania", country_code: "MR", resource_name: "geoTargetConstants/2478"},
      {name: "Mauritius", country_code: "MU", resource_name: "geoTargetConstants/2480"},
      {name: "Mexico", country_code: "MX", resource_name: "geoTargetConstants/2484"},
      {name: "Monaco", country_code: "MC", resource_name: "geoTargetConstants/2492"},
      {name: "Mongolia", country_code: "MN", resource_name: "geoTargetConstants/2496"},
      {name: "Moldova", country_code: "MD", resource_name: "geoTargetConstants/2498"},
      {name: "Montenegro", country_code: "ME", resource_name: "geoTargetConstants/2499"},
      {name: "Morocco", country_code: "MA", resource_name: "geoTargetConstants/2504"},
      {name: "Mozambique", country_code: "MZ", resource_name: "geoTargetConstants/2508"},
      {name: "Oman", country_code: "OM", resource_name: "geoTargetConstants/2512"},
      {name: "Namibia", country_code: "NA", resource_name: "geoTargetConstants/2516"},
      {name: "Nauru", country_code: "NR", resource_name: "geoTargetConstants/2520"},
      {name: "Nepal", country_code: "NP", resource_name: "geoTargetConstants/2524"},
      {name: "Netherlands", country_code: "NL", resource_name: "geoTargetConstants/2528"},
      {name: "Curacao", country_code: "CW", resource_name: "geoTargetConstants/2531"},
      {name: "Sint Maarten", country_code: "SX", resource_name: "geoTargetConstants/2534"},
      {name: "Caribbean Netherlands", country_code: "BQ", resource_name: "geoTargetConstants/2535"},
      {name: "New Caledonia", country_code: "NC", resource_name: "geoTargetConstants/2540"},
      {name: "Vanuatu", country_code: "VU", resource_name: "geoTargetConstants/2548"},
      {name: "New Zealand", country_code: "NZ", resource_name: "geoTargetConstants/2554"},
      {name: "Nicaragua", country_code: "NI", resource_name: "geoTargetConstants/2558"},
      {name: "Niger", country_code: "NE", resource_name: "geoTargetConstants/2562"},
      {name: "Nigeria", country_code: "NG", resource_name: "geoTargetConstants/2566"},
      {name: "Niue", country_code: "NU", resource_name: "geoTargetConstants/2570"},
      {name: "Norfolk Island", country_code: "NF", resource_name: "geoTargetConstants/2574"},
      {name: "Norway", country_code: "NO", resource_name: "geoTargetConstants/2578"},
      {name: "Northern Mariana Islands", country_code: "MP", resource_name: "geoTargetConstants/2580"},
      {name: "United States Minor Outlying Islands", country_code: "UM", resource_name: "geoTargetConstants/2581"},
      {name: "Micronesia", country_code: "FM", resource_name: "geoTargetConstants/2583"},
      {name: "Marshall Islands", country_code: "MH", resource_name: "geoTargetConstants/2584"},
      {name: "Palau", country_code: "PW", resource_name: "geoTargetConstants/2585"},
      {name: "Pakistan", country_code: "PK", resource_name: "geoTargetConstants/2586"},
      {name: "Panama", country_code: "PA", resource_name: "geoTargetConstants/2591"},
      {name: "Papua New Guinea", country_code: "PG", resource_name: "geoTargetConstants/2598"},
      {name: "Paraguay", country_code: "PY", resource_name: "geoTargetConstants/2600"},
      {name: "Peru", country_code: "PE", resource_name: "geoTargetConstants/2604"},
      {name: "Philippines", country_code: "PH", resource_name: "geoTargetConstants/2608"},
      {name: "Pitcairn Islands", country_code: "PN", resource_name: "geoTargetConstants/2612"},
      {name: "Poland", country_code: "PL", resource_name: "geoTargetConstants/2616"},
      {name: "Portugal", country_code: "PT", resource_name: "geoTargetConstants/2620"},
      {name: "Guinea-Bissau", country_code: "GW", resource_name: "geoTargetConstants/2624"},
      {name: "Timor-Leste", country_code: "TL", resource_name: "geoTargetConstants/2626"},
      {name: "Qatar", country_code: "QA", resource_name: "geoTargetConstants/2634"},
      {name: "Romania", country_code: "RO", resource_name: "geoTargetConstants/2642"},
      {name: "Russia", country_code: "RU", resource_name: "geoTargetConstants/2643"},
      {name: "Rwanda", country_code: "RW", resource_name: "geoTargetConstants/2646"},
      {name: "Saint Barthelemy", country_code: "BL", resource_name: "geoTargetConstants/2652"},
      {name: "Saint Helena, Ascension and Tristan da Cunha", country_code: "SH", resource_name: "geoTargetConstants/2654"},
      {name: "Saint Kitts and Nevis", country_code: "KN", resource_name: "geoTargetConstants/2659"},
      {name: "Saint Lucia", country_code: "LC", resource_name: "geoTargetConstants/2662"},
      {name: "Saint Martin", country_code: "MF", resource_name: "geoTargetConstants/2663"},
      {name: "Saint Pierre and Miquelon", country_code: "PM", resource_name: "geoTargetConstants/2666"},
      {name: "Saint Vincent and the Grenadines", country_code: "VC", resource_name: "geoTargetConstants/2670"},
      {name: "San Marino", country_code: "SM", resource_name: "geoTargetConstants/2674"},
      {name: "Sao Tome and Principe", country_code: "ST", resource_name: "geoTargetConstants/2678"},
      {name: "Saudi Arabia", country_code: "SA", resource_name: "geoTargetConstants/2682"},
      {name: "Senegal", country_code: "SN", resource_name: "geoTargetConstants/2686"},
      {name: "Serbia", country_code: "RS", resource_name: "geoTargetConstants/2688"},
      {name: "Seychelles", country_code: "SC", resource_name: "geoTargetConstants/2690"},
      {name: "Sierra Leone", country_code: "SL", resource_name: "geoTargetConstants/2694"},
      {name: "Singapore", country_code: "SG", resource_name: "geoTargetConstants/2702"},
      {name: "Slovakia", country_code: "SK", resource_name: "geoTargetConstants/2703"},
      {name: "Vietnam", country_code: "VN", resource_name: "geoTargetConstants/2704"},
      {name: "Slovenia", country_code: "SI", resource_name: "geoTargetConstants/2705"},
      {name: "Somalia", country_code: "SO", resource_name: "geoTargetConstants/2706"},
      {name: "South Africa", country_code: "ZA", resource_name: "geoTargetConstants/2710"},
      {name: "Zimbabwe", country_code: "ZW", resource_name: "geoTargetConstants/2716"},
      {name: "Spain", country_code: "ES", resource_name: "geoTargetConstants/2724"},
      {name: "South Sudan", country_code: "SS", resource_name: "geoTargetConstants/2728"},
      {name: "Sudan", country_code: "SD", resource_name: "geoTargetConstants/2736"},
      {name: "Suriname", country_code: "SR", resource_name: "geoTargetConstants/2740"},
      {name: "Eswatini", country_code: "SZ", resource_name: "geoTargetConstants/2748"},
      {name: "Sweden", country_code: "SE", resource_name: "geoTargetConstants/2752"},
      {name: "Switzerland", country_code: "CH", resource_name: "geoTargetConstants/2756"},
      {name: "Tajikistan", country_code: "TJ", resource_name: "geoTargetConstants/2762"},
      {name: "Thailand", country_code: "TH", resource_name: "geoTargetConstants/2764"},
      {name: "Togo", country_code: "TG", resource_name: "geoTargetConstants/2768"},
      {name: "Tokelau", country_code: "TK", resource_name: "geoTargetConstants/2772"},
      {name: "Tonga", country_code: "TO", resource_name: "geoTargetConstants/2776"},
      {name: "Trinidad and Tobago", country_code: "TT", resource_name: "geoTargetConstants/2780"},
      {name: "United Arab Emirates", country_code: "AE", resource_name: "geoTargetConstants/2784"},
      {name: "Tunisia", country_code: "TN", resource_name: "geoTargetConstants/2788"},
      {name: "Turkiye", country_code: "TR", resource_name: "geoTargetConstants/2792"},
      {name: "Turkmenistan", country_code: "TM", resource_name: "geoTargetConstants/2795"},
      {name: "Tuvalu", country_code: "TV", resource_name: "geoTargetConstants/2798"},
      {name: "Uganda", country_code: "UG", resource_name: "geoTargetConstants/2800"},
      {name: "Ukraine", country_code: "UA", resource_name: "geoTargetConstants/2804"},
      {name: "North Macedonia", country_code: "MK", resource_name: "geoTargetConstants/2807"},
      {name: "Egypt", country_code: "EG", resource_name: "geoTargetConstants/2818"},
      {name: "United Kingdom", country_code: "GB", resource_name: "geoTargetConstants/2826"},
      {name: "Guernsey", country_code: "GG", resource_name: "geoTargetConstants/2831"},
      {name: "Jersey", country_code: "JE", resource_name: "geoTargetConstants/2832"},
      {name: "Isle of Man", country_code: "IM", resource_name: "geoTargetConstants/2833"},
      {name: "Tanzania", country_code: "TZ", resource_name: "geoTargetConstants/2834"},
      {name: "United States", country_code: "US", resource_name: "geoTargetConstants/2840"},
      {name: "Burkina Faso", country_code: "BF", resource_name: "geoTargetConstants/2854"},
      {name: "Uruguay", country_code: "UY", resource_name: "geoTargetConstants/2858"},
      {name: "Uzbekistan", country_code: "UZ", resource_name: "geoTargetConstants/2860"},
      {name: "Venezuela", country_code: "VE", resource_name: "geoTargetConstants/2862"},
      {name: "Wallis and Futuna", country_code: "WF", resource_name: "geoTargetConstants/2876"},
      {name: "Samoa", country_code: "WS", resource_name: "geoTargetConstants/2882"},
      {name: "Yemen", country_code: "YE", resource_name: "geoTargetConstants/2887"},
      {name: "Zambia", country_code: "ZM", resource_name: "geoTargetConstants/2894"}
    ]
  end

  def language_constants
    [
      {code: "en", name: "English", resource_name: "languageConstants/1000"},
      {code: "de", name: "German", resource_name: "languageConstants/1001"},
      {code: "fr", name: "French", resource_name: "languageConstants/1002"},
      {code: "es", name: "Spanish", resource_name: "languageConstants/1003"},
      {code: "it", name: "Italian", resource_name: "languageConstants/1004"},
      {code: "ja", name: "Japanese", resource_name: "languageConstants/1005"},
      {code: "en_US", name: "English (US)", resource_name: "languageConstants/1006"},
      {code: "en_GB", name: "English (UK)", resource_name: "languageConstants/1007"},
      {code: "zh", name: "Chinese", resource_name: "languageConstants/1008"},
      {code: "da", name: "Danish", resource_name: "languageConstants/1009"},
      {code: "nl", name: "Dutch", resource_name: "languageConstants/1010"},
      {code: "fi", name: "Finnish", resource_name: "languageConstants/1011"},
      {code: "ko", name: "Korean", resource_name: "languageConstants/1012"},
      {code: "no", name: "Norwegian", resource_name: "languageConstants/1013"},
      {code: "pt", name: "Portuguese", resource_name: "languageConstants/1014"},
      {code: "sv", name: "Swedish", resource_name: "languageConstants/1015"},
      {code: "pt_BR", name: "Portuguese (Brazil)", resource_name: "languageConstants/1016"},
      {code: "zh_CN", name: "Chinese (simplified)", resource_name: "languageConstants/1017"},
      {code: "zh_TW", name: "Chinese (traditional)", resource_name: "languageConstants/1018"},
      {code: "ar", name: "Arabic", resource_name: "languageConstants/1019"},
      {code: "bg", name: "Bulgarian", resource_name: "languageConstants/1020"},
      {code: "cs", name: "Czech", resource_name: "languageConstants/1021"},
      {code: "el", name: "Greek", resource_name: "languageConstants/1022"},
      {code: "hi", name: "Hindi", resource_name: "languageConstants/1023"},
      {code: "hu", name: "Hungarian", resource_name: "languageConstants/1024"},
      {code: "id", name: "Indonesian", resource_name: "languageConstants/1025"},
      {code: "is", name: "Icelandic", resource_name: "languageConstants/1026"},
      {code: "iw", name: "Hebrew", resource_name: "languageConstants/1027"},
      {code: "lv", name: "Latvian", resource_name: "languageConstants/1028"},
      {code: "lt", name: "Lithuanian", resource_name: "languageConstants/1029"},
      {code: "pl", name: "Polish", resource_name: "languageConstants/1030"},
      {code: "ru", name: "Russian", resource_name: "languageConstants/1031"},
      {code: "ro", name: "Romanian", resource_name: "languageConstants/1032"},
      {code: "sk", name: "Slovak", resource_name: "languageConstants/1033"},
      {code: "sl", name: "Slovenian", resource_name: "languageConstants/1034"},
      {code: "sr", name: "Serbian", resource_name: "languageConstants/1035"},
      {code: "uk", name: "Ukrainian", resource_name: "languageConstants/1036"},
      {code: "tr", name: "Turkish", resource_name: "languageConstants/1037"},
      {code: "ca", name: "Catalan", resource_name: "languageConstants/1038"},
      {code: "hr", name: "Croatian", resource_name: "languageConstants/1039"},
      {code: "vi", name: "Vietnamese", resource_name: "languageConstants/1040"},
      {code: "ur", name: "Urdu", resource_name: "languageConstants/1041"},
      {code: "tl", name: "Filipino", resource_name: "languageConstants/1042"},
      {code: "et", name: "Estonian", resource_name: "languageConstants/1043"},
      {code: "th", name: "Thai", resource_name: "languageConstants/1044"},
      {code: "aa", name: "Afar", resource_name: "languageConstants/1045"},
      {code: "ab", name: "Abkhazian", resource_name: "languageConstants/1046"},
      {code: "af", name: "Afrikaans", resource_name: "languageConstants/1047"},
      {code: "am", name: "Amharic", resource_name: "languageConstants/1048"},
      {code: "as", name: "Assamese", resource_name: "languageConstants/1049"},
      {code: "ay", name: "Aymara", resource_name: "languageConstants/1050"},
      {code: "az", name: "Azerbaijani", resource_name: "languageConstants/1051"},
      {code: "ba", name: "Bashkir", resource_name: "languageConstants/1052"},
      {code: "be", name: "Belarusian", resource_name: "languageConstants/1053"},
      {code: "bh", name: "Bihari", resource_name: "languageConstants/1054"},
      {code: "bi", name: "Bislama", resource_name: "languageConstants/1055"},
      {code: "bn", name: "Bengali", resource_name: "languageConstants/1056"},
      {code: "bo", name: "Tibetan", resource_name: "languageConstants/1057"},
      {code: "br", name: "Breton", resource_name: "languageConstants/1058"},
      {code: "co", name: "Corsican", resource_name: "languageConstants/1059"},
      {code: "cy", name: "Welsh", resource_name: "languageConstants/1060"},
      {code: "nn", name: "Norwegian Nynorsk", resource_name: "languageConstants/1061"},
      {code: "eo", name: "Esperanto", resource_name: "languageConstants/1062"},
      {code: "eu", name: "Basque", resource_name: "languageConstants/1063"},
      {code: "fa", name: "Persian", resource_name: "languageConstants/1064"},
      {code: "fj", name: "Fijian", resource_name: "languageConstants/1065"},
      {code: "fo", name: "Faroese", resource_name: "languageConstants/1066"},
      {code: "fy", name: "Western Frisian", resource_name: "languageConstants/1067"},
      {code: "ga", name: "Irish", resource_name: "languageConstants/1068"},
      {code: "gd", name: "Scottish Gaelic", resource_name: "languageConstants/1069"},
      {code: "gl", name: "Galician", resource_name: "languageConstants/1070"},
      {code: "gn", name: "Guarani", resource_name: "languageConstants/1071"},
      {code: "gu", name: "Gujarati", resource_name: "languageConstants/1072"},
      {code: "gv", name: "Manx", resource_name: "languageConstants/1073"},
      {code: "ha", name: "Hausa", resource_name: "languageConstants/1074"},
      {code: "bs", name: "Bosnian", resource_name: "languageConstants/1075"},
      {code: "hy", name: "Armenian", resource_name: "languageConstants/1076"},
      {code: "ia", name: "Interlingua", resource_name: "languageConstants/1077"},
      {code: "ie", name: "Interlingue", resource_name: "languageConstants/1078"},
      {code: "ik", name: "Inupiaq", resource_name: "languageConstants/1079"},
      {code: "iu", name: "Inuktitut", resource_name: "languageConstants/1080"},
      {code: "jv", name: "Javanese", resource_name: "languageConstants/1081"},
      {code: "ka", name: "Georgian", resource_name: "languageConstants/1082"},
      {code: "kk", name: "Kazakh", resource_name: "languageConstants/1083"},
      {code: "kl", name: "Greenlandic", resource_name: "languageConstants/1084"},
      {code: "km", name: "Khmer", resource_name: "languageConstants/1085"},
      {code: "kn", name: "Kannada", resource_name: "languageConstants/1086"},
      {code: "ks", name: "Kashmiri", resource_name: "languageConstants/1087"},
      {code: "ku", name: "Kurdish", resource_name: "languageConstants/1088"},
      {code: "kw", name: "Cornish", resource_name: "languageConstants/1089"},
      {code: "ky", name: "Kirghiz", resource_name: "languageConstants/1090"},
      {code: "la", name: "Latin", resource_name: "languageConstants/1091"},
      {code: "lb", name: "Luxembourgish", resource_name: "languageConstants/1092"},
      {code: "ln", name: "Lingala", resource_name: "languageConstants/1093"},
      {code: "lo", name: "Lao", resource_name: "languageConstants/1094"},
      {code: "mg", name: "Malagasy", resource_name: "languageConstants/1095"},
      {code: "mi", name: "Maori", resource_name: "languageConstants/1096"},
      {code: "mk", name: "Macedonian", resource_name: "languageConstants/1097"},
      {code: "ml", name: "Malayalam", resource_name: "languageConstants/1098"},
      {code: "mn", name: "Mongolian", resource_name: "languageConstants/1099"},
      {code: "mo", name: "Moldavian", resource_name: "languageConstants/1100"},
      {code: "mr", name: "Marathi", resource_name: "languageConstants/1101"},
      {code: "ms", name: "Malay", resource_name: "languageConstants/1102"},
      {code: "mt", name: "Maltese", resource_name: "languageConstants/1103"},
      {code: "my", name: "Burmese", resource_name: "languageConstants/1104"},
      {code: "na", name: "Nauru", resource_name: "languageConstants/1105"},
      {code: "ne", name: "Nepali", resource_name: "languageConstants/1106"},
      {code: "oc", name: "Occitan", resource_name: "languageConstants/1107"},
      {code: "om", name: "(Afan) Oromo", resource_name: "languageConstants/1108"},
      {code: "or", name: "Oriya", resource_name: "languageConstants/1109"},
      {code: "pa", name: "Punjabi", resource_name: "languageConstants/1110"},
      {code: "ps", name: "Pushto", resource_name: "languageConstants/1111"},
      {code: "qu", name: "Quechua", resource_name: "languageConstants/1112"},
      {code: "rm", name: "Raeto-Romance", resource_name: "languageConstants/1113"},
      {code: "rn", name: "Rundi", resource_name: "languageConstants/1114"},
      {code: "rw", name: "Kinyarwanda", resource_name: "languageConstants/1115"},
      {code: "sa", name: "Sanskrit", resource_name: "languageConstants/1116"},
      {code: "sd", name: "Sindhi", resource_name: "languageConstants/1117"},
      {code: "se", name: "Northern S�mi", resource_name: "languageConstants/1118"},
      {code: "sg", name: "Sango", resource_name: "languageConstants/1119"},
      {code: "zu", name: "Zulu", resource_name: "languageConstants/1120"},
      {code: "si", name: "Sinhalese", resource_name: "languageConstants/1121"},
      {code: "sm", name: "Samoan", resource_name: "languageConstants/1122"},
      {code: "sn", name: "Shona", resource_name: "languageConstants/1123"},
      {code: "so", name: "Somali", resource_name: "languageConstants/1124"},
      {code: "sq", name: "Albanian", resource_name: "languageConstants/1125"},
      {code: "ss", name: "Swati", resource_name: "languageConstants/1126"},
      {code: "st", name: "Sotho", resource_name: "languageConstants/1127"},
      {code: "su", name: "Sundanese", resource_name: "languageConstants/1128"},
      {code: "sw", name: "Swahili", resource_name: "languageConstants/1129"},
      {code: "ta", name: "Tamil", resource_name: "languageConstants/1130"},
      {code: "te", name: "Telugu", resource_name: "languageConstants/1131"},
      {code: "tg", name: "Tajik", resource_name: "languageConstants/1132"},
      {code: "ti", name: "Tigrinya", resource_name: "languageConstants/1133"},
      {code: "tk", name: "Turkmen", resource_name: "languageConstants/1134"},
      {code: "tn", name: "Tswana", resource_name: "languageConstants/1135"},
      {code: "to", name: "Tonga", resource_name: "languageConstants/1136"},
      {code: "ts", name: "Tsonga", resource_name: "languageConstants/1137"},
      {code: "tt", name: "Tatar", resource_name: "languageConstants/1138"},
      {code: "tw", name: "Twi", resource_name: "languageConstants/1139"},
      {code: "ug", name: "Uighur", resource_name: "languageConstants/1140"},
      {code: "uz", name: "Uzbek", resource_name: "languageConstants/1141"},
      {code: "vo", name: "Volap�k", resource_name: "languageConstants/1142"},
      {code: "wo", name: "Wolof", resource_name: "languageConstants/1143"},
      {code: "xh", name: "Xhosa", resource_name: "languageConstants/1144"},
      {code: "yi", name: "Yiddish", resource_name: "languageConstants/1145"},
      {code: "yo", name: "Yoruba", resource_name: "languageConstants/1146"},
      {code: "za", name: "Zhuang", resource_name: "languageConstants/1147"},
      {code: "en_AU", name: "English (Australia)", resource_name: "languageConstants/1148"},
      {code: "pt_PT", name: "Portuguese (Portugal)", resource_name: "languageConstants/1149"},
      {code: "zh_HK", name: "Chinese (Hong Kong SAR)", resource_name: "languageConstants/1150"}
    ]
  end

end

# Google::Ads::GoogleAds::Config.new do |c|
#   c.developer_token = Rails.application.credentials.google_ads_api_developer_token
#   c.login_customer_id = Rails.application.credentials.google_ads_api_customer_id
#   c.keyfile = './app/services/google_ads/fetchserp-a90b6075bf05.json'
# end