class Ai::Seo::KeywordsService < BaseService
  def call
    # keywords = Ai::Seo::KeywordsService.new.keywords
    keywords.each do |keyword|
      keyword = keyword.downcase
      next if SeoKeyword.find_by(name: keyword).present?
      SeoKeyword.create!(
        name: keyword,
        is_long_tail: false,
        search_intent: "transactional"
      )
    end
  end

  def keywords
    [
      "keywords search",
      "find keywords",
      "keywords google",
      "google ads keywords",
      "domain ranking",
      "ranking keywords",
      "keywords analysis",
      "seo keywords",
      "keywords google ads",
      "search engine keywords",
      "top keywords",
      "search engine",
      "google ads keyword planner",
      "keywords for google ads",
      "google ads keyword search",
      "keywords search google",
      "search volume for keywords",
      "ads keywords",
      "check keywords",
      "keyword ranking google",
      "domain analysis",
      "seo ranking",
      "keywords planner",
      "google search keywords",
      "seo analysis",
      "get keywords",
      "google key word",
      "keywords in google ads",
      "search volume",
      "find keywords for google ads",
      "find search volume of keywords",
      "google planner keywords",
      "keyword search google ads",
      "keyword planner google ads",
      "keyword search ranking",
      "seo ranking keywords",
      "google ads search keywords",
      "google search ranking",
      "google adwords keywords",
      "keyword discovery",
      "google keyword search volume",
      "google seo keywords",
      "search engine rankings",
      "top ranking keywords",
      "rank tracker",
      "ads keyword planner",
      "keyword search tools",
      "key word planner",
      "search ranking",
      "search volume google keywords",
      "trending keywords",
      "top ranking keywords on google",
      "search volume for keywords on google",
      "search engine keywords ranking",
      "seo search keywords",
      "domain keywords",
      "keywords volume",
      "seo keyword research",
      "keywords tracker",
      "google ads tracking",
      "using google ads",
      "keywords planner google ads",
      "google ad keywords planner",
      "search terms",
      "google ads find keywords",
      "google ads analysis",
      "keywords for seo ranking",
      "high ranking keywords",
      "search google ads",
      "my google ads",
      "keyword planner for google ads",
      "google keyword planner google ads",
      "google ads keyword search volume",
      "google ads planner",
      "google ads search",
      "google ad keyword search",
      "google ads and keywords",
      "google ads competitor analysis",
      "google ads seo",
      "seo check",
      "ranking google",
      "google adwords keyword planner",
      "google keyword research planner",
      "search volume keywords google",
      "find keywords of competitors",
      "keyword planner in google ads",
      "all search engines",
      "find google keywords",
      "keyword search terms",
      "keyword search analysis",
      "google seo",
      "keyword competitor analysis",
      "key words",
      "search keywords google ads",
      "ads tracking",
      "volume search keywords",
      "google search volume for keywords",
      "top keywords on google",
      "keyword planner ads",
      "new google ads",
      "competitor tracking",
      "check keyword ranking",
      "google adwords search",
      "set up google ads",
      "keyword tracking tools",
      "get search volume for keywords",
      "google ads start with keywords",
      "sign up google ads",
      "find keyword search volume",
      "keyword monitoring",
      "google ads integration",
      "find seo keywords",
      "seo ai",
      "google keyword planner ads",
      "google ads keyword analysis",
      "google ads data",
      "check google keyword ranking",
      "google ads search volume",
      "google ads google ads google ads",
      "keyword analysis google",
      "google ads keywords plan",
      "google keyword tracker",
      "google google ads",
      "keyword data",
      "keyword search data",
      "domain ranking google",
      "keyword search planner",
      "google keyword planner search volume",
      "keyword planner google ad",
      "key word search",
      "high search volume keywords",
      "keyword suggestions",
      "google ads offer",
      "search engine optimization google",
      "watch keywords",
      "search engine google",
      "google ads keyword planner free",
      "find keywords competitors are using",
      "keyword planner search volume",
      "google search volume",
      "domain keyword search",
      "search competitor keywords",
      "search platform",
      "google ads for your business",
      "google ads reports",
      "keyword volume google",
      "see search volume for keywords",
      "from google ads",
      "ads planner",
      "seo ads",
      "competitor insights",
      "most search keywords on google",
      "google ads google ads",
      "find google keyword search volume",
      "check search volume of keywords",
      "search volume google",
      "check keywords google",
      "all about google ads",
      "search volume of a keyword",
      "keyword ranking in seo",
      "google search engine ads",
      "key word google",
      "google seo keyword ranking",
      "google ads domain",
      "find what keywords competitors are using",
      "search tools",
      "seo tracker",
      "competitor search",
      "competitor analysis google ads",
      "top search keywords",
      "google search engine keywords",
      "keywords on google ads",
      "google search ads keywords",
      "improve your seo",
      "find related keywords",
      "keyword recommendations",
      "tracking google ads",
      "google search keyword planner",
      "google ads ranking",
      "competitor google ads",
      "seo rank tracking tools",
      "generate seo keywords",
      "keywords of competitors",
      "use google keyword planner",
      "google search engines",
      "google search volume keyword",
      "improve your google search ranking",
      "google keyword search planner",
      "see competitors google ads",
      "keyword seo analysis",
      "ad google keyword planner",
      "see google ads of competitors",
      "search pages",
      "page domain",
      "check domain ranking",
      "search for keywords on google",
      "google ad planner keyword search",
      "help google ads",
      "seo performance",
      "google adwords keyword search",
      "competitors google ads",
      "keywords free",
      "top seo keywords",
      "keyword report",
      "most keyword search on google",
      "google keyword search rankings",
      "seo domain",
      "competitor ads analysis",
      "google seo ranking",
      "serp ranking",
      "google ads and seo",
      "check competitors google ads",
      "keywords ads google",
      "google keyword search engine",
      "search engine results page",
      "keyword ranking tracking",
      "search engine optimization keywords",
      "page ranking",
      "a search engine",
      "long tail keyword",
      "seo position tracking",
      "improve search engine ranking",
      "domain seo analysis",
      "search keyword planner",
      "generate keywords",
      "search monitor",
      "find most searched keywords",
      "google keyword search tools",
      "google ads competitor",
      "find ranking keywords",
      "seo lookup",
      "keywords with high search volume",
      "seo and google ads",
      "search terms google",
      "discover keywords google",
      "google ads google keyword planner",
      "my keywords",
      "keyword google ad",
      "google adwords search volume",
      "check keywords search volume",
      "business keywords",
      "google ads insights",
      "keywords and seo",
      "search keywords seo",
      "web page analysis",
      "find search keywords",
      "ads search",
      "search for google ads",
      "with google ads",
      "google ads keyword planner sign up",
      "find top keywords",
      "identify keywords",
      "frequently asked questions",
      "seo check keywords",
      "keywords ai",
      "find search volume",
      "seo results",
      "keyword lists",
      "high ranking keywords search",
      "google ads search engine",
      "your keywords",
      "google & keywords planner",
      "key word seo",
      "google the keyword",
      "seo page",
      "google keyword ranking search",
      "keyword monitoring tools",
      "google seo keywords ranking",
      "google keyword data",
      "seo google keyword planner",
      "the keyword planner",
      "find google ads",
      "search volume google ads",
      "top performing keywords",
      "my seo",
      "ads keyword tool",
      "search search engine",
      "search volume google keyword planner",
      "seo page analysis",
      "find my keywords",
      "we can track",
      "google ads search terms",
      "find keyword volume",
      "check google rankings",
      "google seo keyword planner",
      "plan google ads",
      "google google keyword planner",
      "google search engine ranking",
      "see competitor google ads",
      "find keywords on a page",
      "keyword planner by google",
      "google adwords search terms",
      "rank tracking tools",
      "google ads monitoring",
      "seo keyword tracker",
      "seo analysis competitor",
      "check keywords on a page",
      "track seo performance",
      "most search keywords",
      "keyword pricing",
      "see keyword search volume",
      "keyword search results",
      "keyword estimator",
      "seo optimization keywords",
      "search volume data",
      "seo search ranking",
      "international search engines",
      "keyword position tracking",
      "seo position",
      "find keyword ranking",
      "check keyword volume",
      "key word tracker",
      "find your keywords",
      "keyword search for google",
      "high volume search keywords",
      "top trending keywords on google",
      "check competitors",
      "all keywords",
      "real time keyword ranking",
      "search with google",
      "check ranking",
      "the google keyword planner",
      "check your seo ranking",
      "domain rank tracker",
      "search engine rank tracking",
      "seo check keyword rankings",
      "ranking google ads",
      "google keyword search data",
      "ai keywords",
      "valuable keywords",
      "keyword search planner google",
      "seo analysis report",
      "seo ranking tracking",
      "top search terms",
      "seo find keywords",
      "search keyword volume google",
      "accurate search engine",
      "check seo ranking for keywords",
      "top searched keywords on google",
      "using keywords",
      "search for competitors",
      "high ranking keywords on google",
      "keyword research free trial",
      "seo search engines",
      "keywords from website",
      "domain keyword ranking",
      "domain seo check",
      "tools to search keywords",
      "improve search ranking",
      "check my keywords",
      "your ranking",
      "search engine optimization google ads",
      "keyword analysis google ads",
      "everything about google ads",
      "competitor data",
      "keyword ranking position",
      "keywords help",
      "google seo keywords search",
      "dominate keywords",
      "all google ads",
      "search all search engines",
      "long keywords",
      "highly searched keywords on google",
      "search engine analysis",
      "generate seo report",
      "keyword keywords",
      "competitor check",
      "competitor report",
      "google ranking tracker",
      "search engine keyword ranking",
      "high performing keywords",
      "top trending keywords",
      "get seo keywords",
      "google searches by keyword",
      "common keywords",
      "high keywords",
      "keyword ranking monitoring",
      "most accurate search engine",
      "2 keywords",
      "keywords position",
      "improve your google ranking",
      "watch rank",
      "top keywords search on google",
      "advertising keywords",
      "get keyword suggestions",
      "rank tracker keywords",
      "boost your google ranking",
      "keyword search tracker",
      "keyword opportunities",
      "no google ads",
      "find popular search terms",
      "seo keyword search volume",
      "watch google ads",
      "potential keywords",
      "search trend analysis",
      "keyword optimization google ads",
      "tracking rankings",
      "high volume keywords",
      "seo keywords planner",
      "search watch",
      "searchable keywords",
      "highly searched keywords",
      "seo all in one",
      "search using keywords",
      "google ads you",
      "keywords volume check",
      "generate long tail keywords",
      "seo related keywords",
      "monitoring keyword ranking",
      "monitor keywords ranking",
      "search for keywords google",
      "keywords page",
      "your google ads",
      "google seo keyword research",
      "your search engine",
      "ranking position",
      "keyword planner for google",
      "check domain rank google",
      "search engine ranking position",
      "planner keyword google",
      "seo ranking analysis",
      "keyword search volume data",
      "seo keyword tracking tools",
      "check domain keywords",
      "start with keywords",
      "page keywords",
      "keywords to track",
      "find competitor",
      "search terms ranking",
      "google domain ranking",
      "seo for google ads",
      "create seo",
      "keyword data analysis",
      "check my ranking",
      "find top searched keywords",
      "current keywords",
      "specific keywords",
      "the keyword google",
      "search key word",
      "search rank tracking",
      "check page keywords",
      "finding key words",
      "search terms google ads",
      "google search engine optimization keywords",
      "the search engine",
      "ai seo keywords",
      "search engine keyword tracker",
      "search engine position ranking",
      "track your competitors",
      "seo keyphrases",
      "find ranking",
      "competitor ads google ads",
      "web page keywords",
      "3 keywords",
      "keyword results",
      "google keyword ranking tracker",
      "competitor ranking analysis",
      "keyword keyword planner",
      "seo ranking monitoring",
      "search engine ranking monitor",
      "keywords 2",
      "search volume keyword planner",
      "include keywords",
      "google ranking monitoring",
      "keyword ranking analysis",
      "search engine search engine",
      "monitor search engine rankings",
      "you can track",
      "seo keyword rank tracking",
      "check keyword position",
      "you keyword",
      "google ads keyword volume",
      "position tracking",
      "multiple search engines",
      "rank tracking for seo",
      "most valuable keywords",
      "highest search keywords in google",
      "keywords of google",
      "seo analysis of page",
      "domain backlinks",
      "find most searched keywords google",
      "google search volume data",
      "keyword engine",
      "google seo tracker",
      "top ranking seo",
      "google search watch",
      "analyze web page for keywords",
      "check volume keyword",
      "google ranking analysis",
      "volume of keywords",
      "get related keywords",
      "google search keywords volume",
      "check my keyword ranking",
      "check your keyword ranking",
      "all about keywords",
      "search engine ranking page",
      "most search terms on google",
      "search volume analysis",
      "data search engine",
      "search page for keywords",
      "keywords of seo",
      "search volume tracker",
      "top google search keywords",
      "search web sites",
      "related keywords search",
      "seo keyword ranking check",
      "google keyword discovery",
      "search multiple search engines",
      "boost your rankings",
      "search volume on google",
      "your seo",
      "rank tracking google",
      "google search position",
      "google keyword search analysis",
      "keywords everything",
      "keywords of google search engine",
      "monitor seo",
      "google search ranking updates",
      "make keywords",
      "search engine and",
      "seo how to track rank",
      "domain position",
      "search engine startup",
      "web keywords",
      "major search engines",
      "your search terms",
      "url rank",
      "check your ranking",
      "1 search engine",
      "find keywords google ads",
      "the most searched keywords on google",
      "using google search engine",
      "watch search engine",
      "domain scraping",
      "faq questions",
      "long tail search terms",
      "all google search engines",
      "generate seo",
      "keywords insights",
      "google search top keywords",
      "get search volume",
      "keywords for seo optimization",
      "get keyword volume",
      "improve rankings",
      "google ads my",
      "google search with keywords",
      "keyword tracker seo",
      "keyword free search",
      "page search engine",
      "google ads long tail keywords",
      "google and search",
      "search engine position tracker",
      "rank monitoring",
      "search engine position",
      "keywords in url",
      "2 search engines",
      "search for a keyword",
      "keyword rank tracking tool",
      "domain search volume",
      "keyphrases seo",
      "find a search engine",
      "keyword 1",
      "google ads custom reports",
      "google search competitors",
      "keywords ranking check",
      "keywords for planning",
      "keyword planner ads google",
      "monitor search engine",
      "search position",
      "search www watch",
      "check keyword ranking free",
      "check your search engine ranking",
      "search engine results page serp",
      "rank 1q",
      "search ads keywords",
      "all about search engines",
      "new keywords",
      "check my domain ranking",
      "keyword backlinks",
      "comprehensive seo",
      "track keyword ranking free",
      "seo on page analysis",
      "using keywords for seo",
      "google search engine results",
      "search keyword rank",
      "google ads report api",
      "search engine results",
      "search engine on google",
      "google ads data analysis",
      "daily rank tracking",
      "integrate google ads",
      "get rank",
      "1 keyword",
      "professional keywords",
      "search volume by search engine",
      "using google search",
      "ranking analysis",
      "search engine results page google",
      "seo check rank",
      "seo watch",
      "most search terms",
      "find search engine ranking",
      "startup keywords",
      "keyword search ads",
      "monitoring google ads",
      "google page rankings",
      "any keywords",
      "keyword trend search",
      "search engine monitoring",
      "on search engine",
      "on page seo keywords",
      "search a keyword",
      "search page ranking",
      "keyword google search volume",
      "google ads and",
      "daily keyword rank tracking",
      "free google keyword search volume",
      "50 keywords",
      "search engine all in one",
      "google ads how many keywords",
      "competitor ranking",
      "search google search",
      "set up tracking",
      "top search engine ranking",
      "seo domain ranking",
      "keyword position seo",
      "update search engine",
      "seo keyword monitoring",
      "create keyword",
      "google keyword search terms",
      "google international search engine",
      "google rank update",
      "seo keyword position",
      "improve search",
      "google search engine results page",
      "indexed keywords",
      "search terms analysis",
      "serp search engine",
      "web scraping search engine",
      "most search keyword in google",
      "check your website rank keyword",
      "powerful search engines",
      "on page seo keyword research",
      "faq keywords",
      "improve search engine",
      "all seo",
      "improve keyword ranking",
      "unlimited keyword rank tracking",
      "most search engine",
      "in google ads",
      "search to google",
      "competitors of google ads",
      "to search engines",
      "tail keywords",
      "import google ads",
      "tracker search engine",
      "page rank for keyword",
      "google insights keywords",
      "keywords in url seo",
      "google seo rank tracker",
      "search for the google",
      "position tracking seo",
      "data seo",
      "ranking seo monitoring",
      "content keyword",
      "long tail search keywords",
      "keyword ranking reports",
      "google ads import",
      "free website rank tracker",
      "google ranking position",
      "keywords questions",
      "google search google search google search",
      "it search engine",
      "monitor your competitors",
      "monitoring seo performance",
      "identify the keywords",
      "need to search",
      "check my seo rank",
      "google search google",
      "seo rank tools",
      "www search engines",
      "keyword search volume and competition",
      "for search engine",
      "google search ranking update",
      "i search engine",
      "enter your keywords",
      "search engine are",
      "search engine is",
      "about search engine",
      "track search terms",
      "as search engine",
      "keywords for it",
      "web page search engine",
      "up seo",
      "google competitor search engine",
      "of search engine",
      "search engine what is it",
      "apa itu search engine",
      "indexed pages in search engines",
      "keyword position monitoring",
      "ranking by seo",
      "search a google",
      "insights google ads",
      "search any",
      "search as google",
      "using seo keywords",
      "keywords related to",
      "search for terms",
      "google search google search",
      "google search pages",
      "it related keywords",
      "this is a search engine",
      "google keywords optimization",
      "top 10 keywords",
      "competitor pages",
      "the most search",
      "using keyword planner",
      "competitors of google search engine",
      "search google search google",
      "3 keyword",
      "seo you",
      "analysis of the keyword",
      "the key word",
      "check keyword ranking website",
      "about google search engine",
      "daily keyword tracking",
      "google search keywords analysis",
      "most trending keywords",
      "multiple keywords",
      "ad keyword search",
      "seo top ranking",
      "using search engines",
      "search engine for data",
      "google keyword position",
      "integrated seo",
      "serp keywords",
      "search at google",
      "search engines and search tools",
      "search analysis",
      "google search engine page",
      "google page search",
      "seo progress",
      "competitor seo keywords",
      "keywords news",
      "search engine page results",
      "specific search engines",
      "google ads for seo",
      "google keyword search by location",
      "seo potential",
      "apa itu google keyword planner",
      "check keyword ranking for my site",
      "real time search engine",
      "search for update",
      "domain and seo",
      "ads ranking",
      "google engines",
      "find the search",
      "check page rank for a keyword",
      "find a search",
      "top popular search engines",
      "search discover",
      "seo keywords report",
      "analysis page",
      "number 1 search engine",
      "keyword position ranking",
      "new google search engine",
      "real time seo",
      "top seo ranking",
      "update search",
      "4 search engines",
      "5 keywords",
      "seo and ranking",
      "google in google in google in google",
      "rank your business",
      "search tracker",
      "check google tracking",
      "check if a page is indexed by google",
      "google search engine support",
      "api rankings",
      "search engine find",
      "check if a page is indexed",
      "engine google search",
      "the most asked questions",
      "web page seo check",
      "search rankings tool",
      "google serp rankings",
      "keyword report google ads",
      "google ads keyword report",
      "key words to",
      "overall seo",
      "we seo",
      "keyword analysis report",
      "it key words",
      "key words are",
      "keyword tracking report",
      "search new",
      "seo how many keywords",
      "page 1 ranking",
      "google keyword ranking free",
      "indexed pages",
      "multiple search engines in one",
      "content search keywords",
      "seo yahoo",
      "google serp tracking",
      "keyword tracking free",
      "volume tracking",
      "serp ranking analysis",
      "detailed search engine",
      "free keyword position tracker",
      "enter your search keyword",
      "ranking of web pages in search engines",
      "dns scraping",
      "search term in google ads",
      "google rank position checker",
      "top 3 search engines",
      "check page rankings",
      "ranking web page",
      "a keyword search",
      "30 search engines",
      "keywords related",
      "google ads time",
      "highest rated search engines",
      "html keyword",
      "set tracking",
      "most asked questions",
      "long tail keyword search volume",
      "domain competitors",
      "i need search",
      "keyword integration",
      "most powerful search engines",
      "free trial google ads",
      "search engine engine",
      "seo daily updates",
      "serp rank tracking",
      "most detailed search engine",
      "number of keywords",
      "search engines ads",
      "search volume in google",
    ]
  end
end